---
title: "STAT 456 Homework 1"
author: "Hailey Lee"
date: "02/01/2024"
output: pdf_document
documentclass: article 
geometry: margin=1in
fontsize: 12pt
pagenumber: TRUE
---

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(echo = TRUE)
```

**Instructions:**

1. Please use R to finish all the questions below. Although in some simple cases, you may obtain the solution directly without using R, you still need to provide the corresponding R code.

2. You are liable for missing points if you don't include output;

3. Whenever possible, please run saved variables, so our TA knows if your code goes the right way and assigns partial credits even if your final answer is wrong.

4. Please submit your solutions in .rmd file and .pdf file compiled via the R markdown through Blackboard. 

\newpage

1. What is the output of the following commands? Try to predict the solutions before you type in the commands. We define:

```{R, eval=TRUE}
x <- c(5, 2, 1, 4); xx <- c(1, 10, 15, 18); y <- rev(10:15);
yy <- seq(length = 10, from  = 9, by = 2)
z <- c(TRUE, FALSE, TRUE, TRUE); w <- c("Marie", "Betty", "Peter");
v <- c("I", "list", "key", "standard", "attraction")
```

   (a) 
   ```{R, eval=TRUE}
    order(x)
    sum(x)
    range(x)
    length(y)
    sum(yy)
   ```
   
   
   (b) 
   ```{R, eval=TRUE}
    c(xx, yy, 12)
   ```


   (c) 
   ```{R, eval=TRUE}
    xx - x
    c(x, 12) * y
    1:6 + 1
    1:9 + 1:2
    log(xx)
   ```


   (d) 
   ```{R, eval=TRUE}
    x <= 2
    (x < 2) & z
    x < (2 & z)
    (x == 1) + 2
   ```


   (e) 
   ```{R, eval=TRUE}
    substring(w, 2, 4)
    paste(substring(w,1,2), substring(w, 5, 5), sep = "..")
    paste(substring(v, 1, 2), collapse = " ")
   ```
  
   
   (f)
   ```{R, eval=TRUE}
    rbind(x,xx)
    cbind(2, 6:1, rep(c(3, 1, 4), 2), seq(1, 1.6, by = 0.05))
   ```



2. Give the R commands to do the following:

   (a)  Use `rep()` to create a vector that has the following elements: 2.7, 8.0, 3.0, 2.7, 8.0, 3.0.
```{R, eval=TRUE}
rep(c(2.7, 8.0, 3.0), times = 2)
```


   (b) Use `seq()` with the length.out argument to create a vector that has the following elements: 0.0, 0.5, 1.0, 1.5, 2.0.
```{R, eval=TRUE}
seq(0.0, 2.0, by = 0.5)
```


   (c) Let `x` be a vector of length three or greater that contains numeric elements. Write some R commands that calculate the sample mean of all of the elements of `x` except the smallest and largest. For example, if `x = (1,2,4,5,6,7)`, you should output the mean of `(2,4,5,6)`. If `x = (1,1,2,3,4,4)`, you should output the mean of `x = (2,3)`. [Hint: Make use of `which`, `min`, `max`, `mean`.]
```{R, eval=TRUE}
x <- c(1, 1, 2, 3, 4, 4)
mean(x[-c(which.max(x), which.min(x))])
```


   (d) Let `x` be a vector containing numerical elements, each of which is a positive integer. Write a single line of R code that replaces each element that is a perfect square with zero.  For example, if `x=(1,2,3,4)`, then you should return `(0,2,3,0)`.
```{R, eval=TRUE}
x <- 1:4
x[sqrt(x)%%1 == 0] <- 0
x
```



3. Suppose you have been keeping track your study times for over three weeks (20 days) and you find the following times in hours:

   ```
   7  10  12  5  6  9.5  13  15  8  11  6  8.5  3  9  14  9.5 10.5  6  7.5  12
   ```

   Use R to answer the following questions.

   (a)  Use the function `max` and `min` to find the longest and shortest study time, the function  `mean` and `median` to find the average and the median number.
```{R, eval=TRUE}
study <- c(7, 10, 12, 5, 6, 9.5, 13, 15, 8, 11, 6, 8.5, 3, 9, 14, 9.5, 10.5, 6, 7.5, 12)
max(study)
min(study)
mean(study)
median(study)
```

   (b)  The 10.5 was a mistake. It should have been 13. How can you fix this? Do so, and then find the new average.
```{R, eval=TRUE}
study[study==10.5]<-13
mean(study)
```


   (c)  How many times was your study time 10 hours or more a day?
```{R, eval=TRUE}
sum(study >= 10)
```


   (d)  What percent of your study time are less than 8 hours/day?
```{R, eval=TRUE}
(sum(study < 8)/length(study))*100
```



4. Your department's utility bill varies from Jan to Dec. Suppose it has the following monthly amounts:

   ```
   20 33 37 31 32 30 NA 47 41 33 48 52
   ```
   
   Enter this data into a variable called `Utility`.
```{R, eval=TRUE}
Utility <- c(20, 33, 37, 31, 32, 30, NA, 47, 41, 33, 48, 52)
Utility
```
   
   
   (a)  Give labels for each value from Jan to Dec (use abbreviation).[Hint: Make use of `month.abb`.]
```{R, eval=TRUE}
names(Utility) <- month.abb
Utility
```


   (b)  We missed one bill for July, replace the number with the mean of the yearly bill (11 months). [Hint: Make use of the `na.rm` option in the `mean`} function.]
```{R, eval=TRUE}
Utility["Jul"] <- mean(Utility, na.rm=TRUE)
Utility
```
   
   
   (c)  After updated the new data using part (b), what is the variance of the yearly bill (12 months)? What is the standard deviation (12 months)?
```{R, eval=TRUE}
var(Utility)
sd(Utility)
```



5. The built-in data set `mtcars` contains information about cars from a 1974 Motor Trend issue. Load the dataset (`data(mtcars)`) and try to answer the following:
```{R, eval=FALSE}
data(mtcars)
```
 
 
   (a)  What are the variable names? (Try `names`.)
```{R, eval=TRUE}
names(mtcars)
```


   (b)  What is the maximum mpg?
```{R, eval=TRUE}
max(mtcars$mpg)
```


   (c)  Which car has this?
```{R, eval=TRUE}
rownames(mtcars[mtcars$mpg == 33.9,])
```


   (d)  What horsepower (hp) does the `Valiant` have?
```{R, eval=TRUE}
mtcars["Valiant",]$hp
```


   (e)  What are the first 5 cars listed?
```{R, eval=TRUE}
mtcars[1:5,]
```


   (f)  What are all the values for the Mercedes 450slc (`Merc 450SLC`)?
```{R, eval=TRUE}
mtcars[rownames(mtcars) == "Merc 450SLC",]
```


6. In `library(lattice)`, there is a build-in dataset named `barley`, which is a data frame with 120 observations on the following 4 variables.

   * `yield`: Yield (averaged across three blocks) in bushels/acre.

   * `variety`: Factor with levels `Svansota`, `No. 462`, `Manchuria`, `No. 475`, `Velvet`, `Peatland`, `Glabron`, `No. 457`, `Wisconsin No. 38`, `Trebi`.

   * `year`: Factor with levels 1932, 1931.

   * `site`: Factor with 6 levels: `Grand Rapids`, `Duluth`, `University Farm`, `Morris`, `Crookston`, `Waseca`.

   ```{R, eval=TRUE}
	library(lattice)
	data(barley)
   ```


   (a) For variable `yield`, find the mean, standard deviation and quantiles of at 10, 20, 30, ..., 90%.
```{R, eval=TRUE}
mean(barley$yield)
sd(barley$yield)
quantile(barley$yield, na.rm = TRUE, c(0.10, 0.20, 0.30, 0.40, 0.50, 0.60, 0.70, 0.80, 0.90))
```


   (b) For values of `yield` obtained in 1931, find the mean, standard deviation and quantiles of at 10, 20, 30, ..., 90%. Repeat the above for values of `yield` obtained in 1932.
```{R, eval=TRUE}
mean(barley[barley$year == 1931,]$yield)
sd(barley[barley$year == 1931,]$yield)
quantile(barley[barley$year == 1931,]$yield, na.rm = TRUE, c(0.10, 0.20, 0.30, 0.40, 0.50, 0.60, 0.70, 0.80, 0.90))

mean(barley[barley$year == 1932,]$yield)
sd(barley[barley$year == 1932,]$yield)
quantile(barley[barley$year == 1932,]$yield, na.rm = TRUE, c(0.10, 0.20, 0.30, 0.40, 0.50, 0.60, 0.70, 0.80, 0.90))
```


   (c) Retrieve all rows of the Barley data in 1931 where the yield lies above the 90% quantile calculated in (b) and name it as `df`.
```{R, eval=TRUE}
df <- barley[barley$year == 1931 & barley$yield > 49.90334,]
df
```

 